/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package info5100.university.example.ui;

import info5100.university.example.CourseSchedule.Seat;

/**
 *
 * @author Ankita
 */
public class CourseReviewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CourseReview
     */
    
    int ratingQ1;
    int ratingQ2;
    int ratingQ3;
    int ratingQ4;
    String feedback;
    Seat seat;
    
    public CourseReviewJPanel(Seat s) {
        initComponents();
        ratingQ1 = 0;
        ratingQ2 = 0;
        ratingQ3 = 0;
        ratingQ4 = 0;
        feedback = "";
        seat = s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupQ1 = new javax.swing.ButtonGroup();
        btnGroupQ2 = new javax.swing.ButtonGroup();
        btnGroupQ3 = new javax.swing.ButtonGroup();
        btnGroupQ4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtFeedback = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jRadioBtn1 = new javax.swing.JRadioButton();
        jRadioBtn2 = new javax.swing.JRadioButton();
        jRadioBtn3 = new javax.swing.JRadioButton();
        jRadioBtn4 = new javax.swing.JRadioButton();
        jRadioBtn5 = new javax.swing.JRadioButton();
        jRadioBtn9 = new javax.swing.JRadioButton();
        jRadioBtn10 = new javax.swing.JRadioButton();
        jRadioBtn8 = new javax.swing.JRadioButton();
        jRadioBtn7 = new javax.swing.JRadioButton();
        jRadioBtn6 = new javax.swing.JRadioButton();
        jRadioBtn14 = new javax.swing.JRadioButton();
        jRadioBtn15 = new javax.swing.JRadioButton();
        jRadioBtn13 = new javax.swing.JRadioButton();
        jRadioBtn12 = new javax.swing.JRadioButton();
        jRadioBtn11 = new javax.swing.JRadioButton();
        jRadioBtn19 = new javax.swing.JRadioButton();
        jRadioBtn20 = new javax.swing.JRadioButton();
        jRadioBtn18 = new javax.swing.JRadioButton();
        jRadioBtn17 = new javax.swing.JRadioButton();
        jRadioBtn16 = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(200, 238, 251));

        jPanel1.setBackground(new java.awt.Color(200, 238, 251));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Course Review");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/info5100/university/example/images/review.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/info5100/university/example/images/review.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/info5100/university/example/images/review.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/info5100/university/example/images/review.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );

        jPanel2.setBackground(new java.awt.Color(200, 238, 251));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setText("Do you feel the instructor was well prepared for the class?");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setText("The instructor showed interest in helping students to learn");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setText("I received feedback on my performance on tests, quizzes, assignments");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel5.setText("Would you recommend this course to other students?");

        txtFeedback.setColumns(20);
        txtFeedback.setRows(5);
        jScrollPane1.setViewportView(txtFeedback);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel6.setText("Additional feedback you would like to recommend:");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnGroupQ1.add(jRadioBtn1);
        jRadioBtn1.setText("Not at all");
        jRadioBtn1.setToolTipText("");
        jRadioBtn1.setContentAreaFilled(false);
        jRadioBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBtn1ActionPerformed(evt);
            }
        });

        btnGroupQ1.add(jRadioBtn2);
        jRadioBtn2.setText("Rarely");
        jRadioBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBtn2ActionPerformed(evt);
            }
        });

        btnGroupQ1.add(jRadioBtn3);
        jRadioBtn3.setText("Sometimes");
        jRadioBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBtn3ActionPerformed(evt);
            }
        });

        btnGroupQ1.add(jRadioBtn4);
        jRadioBtn4.setText("Frequently");
        jRadioBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBtn4ActionPerformed(evt);
            }
        });

        btnGroupQ1.add(jRadioBtn5);
        jRadioBtn5.setText("Almost Always ");
        jRadioBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBtn5ActionPerformed(evt);
            }
        });

        btnGroupQ2.add(jRadioBtn9);
        jRadioBtn9.setText("Frequently");
        jRadioBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBtn9ActionPerformed(evt);
            }
        });

        btnGroupQ2.add(jRadioBtn10);
        jRadioBtn10.setText("Almost Always ");
        jRadioBtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBtn10ActionPerformed(evt);
            }
        });

        btnGroupQ2.add(jRadioBtn8);
        jRadioBtn8.setText("Sometimes");
        jRadioBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBtn8ActionPerformed(evt);
            }
        });

        btnGroupQ2.add(jRadioBtn7);
        jRadioBtn7.setText("Rarely");
        jRadioBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBtn7ActionPerformed(evt);
            }
        });

        btnGroupQ2.add(jRadioBtn6);
        jRadioBtn6.setText("Not at all");
        jRadioBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBtn6ActionPerformed(evt);
            }
        });

        btnGroupQ3.add(jRadioBtn14);
        jRadioBtn14.setText("Frequently");

        btnGroupQ3.add(jRadioBtn15);
        jRadioBtn15.setText("Almost Always ");
        jRadioBtn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBtn15ActionPerformed(evt);
            }
        });

        btnGroupQ3.add(jRadioBtn13);
        jRadioBtn13.setText("Sometimes");
        jRadioBtn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBtn13ActionPerformed(evt);
            }
        });

        btnGroupQ3.add(jRadioBtn12);
        jRadioBtn12.setText("Rarely");
        jRadioBtn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBtn12ActionPerformed(evt);
            }
        });

        btnGroupQ3.add(jRadioBtn11);
        jRadioBtn11.setText("Not at all");
        jRadioBtn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBtn11ActionPerformed(evt);
            }
        });

        btnGroupQ4.add(jRadioBtn19);
        jRadioBtn19.setText("Frequently");
        jRadioBtn19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBtn19ActionPerformed(evt);
            }
        });

        btnGroupQ4.add(jRadioBtn20);
        jRadioBtn20.setText("Almost Always ");
        jRadioBtn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBtn20ActionPerformed(evt);
            }
        });

        btnGroupQ4.add(jRadioBtn18);
        jRadioBtn18.setText("Sometimes");
        jRadioBtn18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBtn18ActionPerformed(evt);
            }
        });

        btnGroupQ4.add(jRadioBtn17);
        jRadioBtn17.setText("Rarely");
        jRadioBtn17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBtn17ActionPerformed(evt);
            }
        });

        btnGroupQ4.add(jRadioBtn16);
        jRadioBtn16.setText("Not at all");
        jRadioBtn16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBtn16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSubmit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioBtn16)
                        .addGap(30, 30, 30)
                        .addComponent(jRadioBtn17)
                        .addGap(26, 26, 26)
                        .addComponent(jRadioBtn18)
                        .addGap(33, 33, 33)
                        .addComponent(jRadioBtn19)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioBtn20))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioBtn11)
                        .addGap(30, 30, 30)
                        .addComponent(jRadioBtn12)
                        .addGap(26, 26, 26)
                        .addComponent(jRadioBtn13)
                        .addGap(33, 33, 33)
                        .addComponent(jRadioBtn14)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioBtn15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioBtn6)
                        .addGap(30, 30, 30)
                        .addComponent(jRadioBtn7)
                        .addGap(26, 26, 26)
                        .addComponent(jRadioBtn8)
                        .addGap(33, 33, 33)
                        .addComponent(jRadioBtn9)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioBtn10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioBtn1)
                        .addGap(30, 30, 30)
                        .addComponent(jRadioBtn2)
                        .addGap(26, 26, 26)
                        .addComponent(jRadioBtn3)
                        .addGap(33, 33, 33)
                        .addComponent(jRadioBtn4)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioBtn5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioBtn1)
                    .addComponent(jRadioBtn2)
                    .addComponent(jRadioBtn3)
                    .addComponent(jRadioBtn4)
                    .addComponent(jRadioBtn5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioBtn6)
                    .addComponent(jRadioBtn7)
                    .addComponent(jRadioBtn8)
                    .addComponent(jRadioBtn9)
                    .addComponent(jRadioBtn10))
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioBtn11)
                    .addComponent(jRadioBtn12)
                    .addComponent(jRadioBtn13)
                    .addComponent(jRadioBtn14)
                    .addComponent(jRadioBtn15))
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioBtn16)
                    .addComponent(jRadioBtn17)
                    .addComponent(jRadioBtn18)
                    .addComponent(jRadioBtn19)
                    .addComponent(jRadioBtn20))
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSubmit)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBtn1ActionPerformed
        // TODO add your handling code here:
        ratingQ1 = 1;
    }//GEN-LAST:event_jRadioBtn1ActionPerformed

    private void jRadioBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBtn2ActionPerformed
        // TODO add your handling code here:
        ratingQ1 = 2;
    }//GEN-LAST:event_jRadioBtn2ActionPerformed

    private void jRadioBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBtn3ActionPerformed
        // TODO add your handling code here:
        ratingQ1 = 3;
    }//GEN-LAST:event_jRadioBtn3ActionPerformed

    private void jRadioBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBtn8ActionPerformed
        // TODO add your handling code here:
        ratingQ2 = 3;
    }//GEN-LAST:event_jRadioBtn8ActionPerformed

    private void jRadioBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBtn7ActionPerformed
        // TODO add your handling code here:
        ratingQ2 = 2;
    }//GEN-LAST:event_jRadioBtn7ActionPerformed

    private void jRadioBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBtn6ActionPerformed
        // TODO add your handling code here:
        ratingQ2 = 1;
    }//GEN-LAST:event_jRadioBtn6ActionPerformed

    private void jRadioBtn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBtn13ActionPerformed
        // TODO add your handling code here:
        ratingQ3 = 3;
    }//GEN-LAST:event_jRadioBtn13ActionPerformed

    private void jRadioBtn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBtn12ActionPerformed
        // TODO add your handling code here:
        ratingQ3 = 2;
    }//GEN-LAST:event_jRadioBtn12ActionPerformed

    private void jRadioBtn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBtn11ActionPerformed
        // TODO add your handling code here:
        ratingQ3 = 1;
    }//GEN-LAST:event_jRadioBtn11ActionPerformed

    private void jRadioBtn18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBtn18ActionPerformed
        // TODO add your handling code here:
        ratingQ4 = 3;
    }//GEN-LAST:event_jRadioBtn18ActionPerformed

    private void jRadioBtn17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBtn17ActionPerformed
        // TODO add your handling code here:
        ratingQ4 = 2;
    }//GEN-LAST:event_jRadioBtn17ActionPerformed

    private void jRadioBtn16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBtn16ActionPerformed
        // TODO add your handling code here:
        ratingQ4 = 1;
    }//GEN-LAST:event_jRadioBtn16ActionPerformed

    private void jRadioBtn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBtn20ActionPerformed
        // TODO add your handling code here:
        ratingQ4 = 5;
    }//GEN-LAST:event_jRadioBtn20ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        int answeredQuestions = 0;
        int overallFeedback = 0;
        if (ratingQ1 > 0) answeredQuestions++;
        if (ratingQ2 > 0) answeredQuestions++;
        if (ratingQ3 > 0) answeredQuestions++;
        if (ratingQ4 > 0) answeredQuestions++;
        if (answeredQuestions > 0)
            overallFeedback = (int)((ratingQ1 + ratingQ2 + ratingQ3 + ratingQ4)*2 / answeredQuestions);
        seat.addReview(overallFeedback, txtFeedback.getText());
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void jRadioBtn19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBtn19ActionPerformed
        // TODO add your handling code here:
        ratingQ4 = 4;
    }//GEN-LAST:event_jRadioBtn19ActionPerformed

    private void jRadioBtn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBtn15ActionPerformed
        // TODO add your handling code here:
        ratingQ3 = 5;
    }//GEN-LAST:event_jRadioBtn15ActionPerformed

    private void jRadioBtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBtn10ActionPerformed
        // TODO add your handling code here:
        ratingQ2 = 5;
    }//GEN-LAST:event_jRadioBtn10ActionPerformed

    private void jRadioBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBtn9ActionPerformed
        // TODO add your handling code here:
        ratingQ2 = 4;
    }//GEN-LAST:event_jRadioBtn9ActionPerformed

    private void jRadioBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBtn5ActionPerformed
        // TODO add your handling code here:
        ratingQ1 = 5;
    }//GEN-LAST:event_jRadioBtn5ActionPerformed

    private void jRadioBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBtn4ActionPerformed
        // TODO add your handling code here:
        ratingQ1 = 4;
    }//GEN-LAST:event_jRadioBtn4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupQ1;
    private javax.swing.ButtonGroup btnGroupQ2;
    private javax.swing.ButtonGroup btnGroupQ3;
    private javax.swing.ButtonGroup btnGroupQ4;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioBtn1;
    private javax.swing.JRadioButton jRadioBtn10;
    private javax.swing.JRadioButton jRadioBtn11;
    private javax.swing.JRadioButton jRadioBtn12;
    private javax.swing.JRadioButton jRadioBtn13;
    private javax.swing.JRadioButton jRadioBtn14;
    private javax.swing.JRadioButton jRadioBtn15;
    private javax.swing.JRadioButton jRadioBtn16;
    private javax.swing.JRadioButton jRadioBtn17;
    private javax.swing.JRadioButton jRadioBtn18;
    private javax.swing.JRadioButton jRadioBtn19;
    private javax.swing.JRadioButton jRadioBtn2;
    private javax.swing.JRadioButton jRadioBtn20;
    private javax.swing.JRadioButton jRadioBtn3;
    private javax.swing.JRadioButton jRadioBtn4;
    private javax.swing.JRadioButton jRadioBtn5;
    private javax.swing.JRadioButton jRadioBtn6;
    private javax.swing.JRadioButton jRadioBtn7;
    private javax.swing.JRadioButton jRadioBtn8;
    private javax.swing.JRadioButton jRadioBtn9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtFeedback;
    // End of variables declaration//GEN-END:variables
}
